version: '3.8'
services:
  filebeat:
    build: filebeat/.
    image: johnwr/filebeat:7.7.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro            # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                        # Additional information about containers
    extra_hosts:
      - "elasticsearch:167.172.35.36"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
  inventory-service:
    image: johnwr/mssc-beer-inventory-service
    ports:
      - '8082:8082'
    environment:
      SPRING_PROFILES_ACTIVE: digitalocean
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@142.93.129.11:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"inventory-service"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"brewery-config"},"failFast":true,"username":"MyUserName","password":"MySecretPassword"}}},"application":{"name":"inventory-service"}}'
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      replicas: 2
  inventory-failover:
    image: johnwr/mssc-inventory-failover
    ports:
      - '8083:8083'
    environment:
      SPRING_PROFILES_ACTIVE: digitalocean
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@142.93.129.11:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"inventory-failover"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"brewery-config"},"failFast":true,"username":"MyUserName","password":"MySecretPassword"}}},"application":{"name":"inventory-failover"}}'
    deploy:
      replicas: 2
  beer-service:
    image: johnwr/mssc-beer-service
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: digitalocean
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@142.93.129.11:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"beer-service"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"brewery-config"},"failFast":true,"username":"MyUserName","password":"MySecretPassword"}}},"application":{"name":"beer-service"}}'
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      replicas: 2
  order-service:
    image: johnwr/mssc-beer-order-service
    ports:
      - '8081:8081'
    environment:
      SPRING_PROFILES_ACTIVE: digitalocean
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@142.93.129.11:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"order-service"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"brewery-config"},"failFast":true,"username":"MyUserName","password":"MySecretPassword"}}},"application":{"name":"order-service"}}'
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      replicas: 2
  gateway:
    image: johnwr/mssc-brewery-gateway
    ports:
      - '9090:9090'
    environment:
      SPRING_PROFILES_ACTIVE: digitalocean
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@142.93.129.11:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"gateway"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"brewery-config"},"failFast":true,"username":"MyUserName","password":"MySecretPassword"}}},"application":{"name":"gateway"}}'
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      replicas: 2
